// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByAo5zDcEmuTNZTrngXEuyuKPHrKzajCQ',
    appId: '1:873608850119:web:f9157fac1e4c6529faace2',
    messagingSenderId: '873608850119',
    projectId: 'tutor-45d54',
    authDomain: 'tutor-45d54.firebaseapp.com',
    databaseURL: 'https://tutor-45d54-default-rtdb.firebaseio.com',
    storageBucket: 'tutor-45d54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2CkdKhCkUri2o48Q0vulG1t9GiykfuI',
    appId: '1:873608850119:android:926d70bb4c0f5fc7faace2',
    messagingSenderId: '873608850119',
    projectId: 'tutor-45d54',
    databaseURL: 'https://tutor-45d54-default-rtdb.firebaseio.com',
    storageBucket: 'tutor-45d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0I5khmlMCFUBMAEV3fX0RSewi4DnAmC8',
    appId: '1:873608850119:ios:c93393fb3b77418bfaace2',
    messagingSenderId: '873608850119',
    projectId: 'tutor-45d54',
    databaseURL: 'https://tutor-45d54-default-rtdb.firebaseio.com',
    storageBucket: 'tutor-45d54.appspot.com',
    iosBundleId: 'com.aries.tutorMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0I5khmlMCFUBMAEV3fX0RSewi4DnAmC8',
    appId: '1:873608850119:ios:3c0d00fc6d25c6aafaace2',
    messagingSenderId: '873608850119',
    projectId: 'tutor-45d54',
    databaseURL: 'https://tutor-45d54-default-rtdb.firebaseio.com',
    storageBucket: 'tutor-45d54.appspot.com',
    iosBundleId: 'com.aries.tutorMobile.RunnerTests',
  );
}
